language: java

jdk:
  - openjdk7

addons:
  postgresql: "9.1"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y bowtie

before_script:
  - export PATH=$PATH:$PWD/resources/
  - psql -c 'create database c5dv151_vt14;' -U postgres
  - psql -f sql/genomizer_database_tables.sql -U postgres -d c5dv151_vt14

script:
  - ant test
