language: java
sudo: false

jdk:
  - openjdk7

addons:
  postgresql: "9.4"

before_script:
  - export PATH=$PATH:$PWD/resources/
  - psql -c 'create database c5dv151_vt14;' -U postgres
  - psql -f sql/genomizer_database_tables.sql -U postgres -d c5dv151_vt14 > /dev/null

script:
  - ant test
  - psql -f sql/drop_all_tables.sql -U postgres -d c5dv151_vt14 > /dev/null
  - psql -f sql/genomizer_database_tables.sql -U postgres -d c5dv151_vt14 > /dev/null
  - psql -f sql/add_test_tuples.sql -U postgres -d c5dv151_vt14 > /dev/null
  - psql -f sql/release_database_tuple.sql -U postgres -d c5dv151_vt14 > /dev/null
  - sed -f travis.sed <settings.cfg.template >settings.cfg
  - ant run 2>&1 > log.txt &
  - cd genomizer-server-tester
  - ant jar
  - java -jar genomizer-server-tester.jar "http://localhost:7000"
  - cat ../log.txt
  - cat ../errorLog.txt
