language: java
sudo: required
dist: trusty

services:
  - docker

jdk:
  - openjdk7

addons:
  postgresql: "9.4"
  apt:
    packages:
      - expect

before_script:
  - export PATH=$PATH:$PWD/resources/
#  - psql -c 'create database c5dv151_vt14;' -U postgres
#  - psql -f sql/genomizer_database_tables.sql -U postgres -d c5dv151_vt14 > /dev/null

script:
  - ant jar
#  - ant test
#  - mkdir cert && cd cert && ../deployment/generate_certificates.expect && cd ..
  - ant -v deploy
  - docker ps
  - docker version
  - docker info
  - docker inspect genomizer-postgres
  - docker inspect genomizer-server
  - docker exec genomizer-server cat /etc/hosts
  - docker exec genomizer-server env
#  - docker inspect genomizer-nginx
  - cd genomizer-server-tester && ant -Dserver="https://localhost:8080" run
  - docker logs genomizer-postgres
  - docker logs genomizer-server
#  - docker logs genomizer-nginx

after_success:
  - git config --global user.email "builds@travis-ci.org"
  - git config --global user.name "Travis CI User"
  - mkdir -p /tmp/deploy
  - cp server.jar /tmp/deploy/genomizer-server.jar
  - cd /tmp/deploy
  - git init
  - git add .
  - git commit -m "Deploy to GitHub ($(date))."
  - test $TRAVIS_PULL_REQUEST == "false" && (test $TRAVIS_BRANCH == "master" || test $TRAVIS_BRANCH == "develop") && git push --force --quiet git@github.com:genomizer/genomizer-downloads.git "master:genomizer-server-$TRAVIS_BRANCH"
