language: java
sudo: false

jdk:
  - openjdk7

addons:
  postgresql: "9.4"

env:
  - DBUSER=genomizer DBNAME=genomizerdb

before_install:
  - ./travis/install_deploy_key

before_script:
  - ./travis/init_postgres

script:
  - ant test
  - ./travis/repopulate_postgres
  - mv settings.cfg.travis settings.cfg
  - ant run 2>&1 > log.txt &
  - cd genomizer-server-tester
  - ant -Dserver="http://localhost:7000" run
  - cd ..
  - cat log.txt
  - cat errorLog.txt

after_success:
  - ./travis/deploy_jars
