language: java
sudo: false

jdk:
  - openjdk7

addons:
  postgresql: "9.4"

before_install:
  - openssl aes-256-cbc -K $encrypted_159a1b5319b6_key -iv $encrypted_159a1b5319b6_iv -in deploy_key.aes256.enc -out id_rsa -d
  - mv id_rsa ~/.ssh/id_rsa
  - chmod 400 ~/.ssh/id_rsa

before_script:
  - export PATH=$PATH:$PWD/resources/
  - psql -c 'create database c5dv151_vt14;' -U postgres
  - psql -f sql/genomizer_database_tables.sql -U postgres -d c5dv151_vt14 > /dev/null

script:
  - ant test
  - psql -f sql/drop_all_tables.sql -U postgres -d c5dv151_vt14 > /dev/null
  - psql -f sql/genomizer_database_tables.sql -U postgres -d c5dv151_vt14 > /dev/null
  - psql -f sql/add_test_tuples.sql -U postgres -d c5dv151_vt14 > /dev/null
  - psql -f sql/release_database_tuple.sql -U postgres -d c5dv151_vt14 > /dev/null
  - sed -f travis.sed <settings.cfg.template >settings.cfg
  - ant run 2>&1 > log.txt &
  - cd genomizer-server-tester
  - ant jar
  - java -jar genomizer-server-tester.jar "http://localhost:7000"
  - cd ..
  - cat log.txt
  - cat errorLog.txt

after_success:
  - git config --global user.email "builds@travis-ci.org"
  - git config --global user.name "Travis CI User"
  - mkdir -p /tmp/deploy
  - cp server.jar /tmp/deploy/genomizer-server.jar
  - cp settings.cfg /tmp/deploy/settings.cfg
  - cd /tmp/deploy
  - git init
  - git add .
  - git commit -m "Deploy to GitHub ($(date))."
  - test $TRAVIS_PULL_REQUEST == "false" && (test $TRAVIS_BRANCH == "master" || test $TRAVIS_BRANCH == "develop") && git push --force --quiet git@github.com:genomizer/genomizer-downloads.git "master:genomizer-server-$TRAVIS_BRANCH"
