#! /bin/bash

set -e

if [[ $TRAVIS_PULL_REQUEST == "false" \
      && ($TRAVIS_BRANCH == "master" || $TRAVIS_BRANCH == "develop") ]]; then

    openssl aes-256-cbc -K $encrypted_159a1b5319b6_key -iv \
        $encrypted_159a1b5319b6_iv -in travis/deploy_key.aes256.enc \
        -out id_rsa -d
    mv id_rsa ~/.ssh/id_rsa
    chmod 400 ~/.ssh/id_rsa
fi
